# Generated by Django 5.1.5 on 2025-01-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensescategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='expensescategory',
            name='icon_expenses',
            field=models.ImageField(default='default_icon.png', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='expensescategory',
            name='icon_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='icon_income',
            field=models.ImageField(default='default_icon.png', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='icon_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
