# Generated by Django 5.1.5 on 2025-01-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0002_remove_expensescategory_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecategory',
            name='icon_income',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_api.incomecategory'),
        ),
        migrations.CreateModel(
            name='ExpensesSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon_expenses', models.ImageField(default='default_icon.png', upload_to='icons/')),
                ('icon_url', models.CharField(default='', max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_api.expensescategory')),
            ],
            options={
                'db_table': 'expenses_sub_categories',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_api.expensessubcategory'),
        ),
        migrations.CreateModel(
            name='IncomeSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon_income', models.ImageField(default='default_icon.png', upload_to='icons/')),
                ('icon_url', models.CharField(default='', max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_api.incomecategory')),
            ],
            options={
                'db_table': 'income_sub_categories',
            },
        ),
        migrations.AddField(
            model_name='income',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_api.incomesubcategory'),
        ),
    ]
