# Generated by Django 5.1.5 on 2025-01-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0003_remove_incomecategory_icon_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensescategory',
            name='icon_expenses',
        ),
        migrations.RemoveField(
            model_name='expensescategory',
            name='icon_url',
        ),
    ]
