# Generated by Django 5.1.5 on 2025-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0004_remove_expensescategory_icon_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensescategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
