# Generated by Django 5.1.5 on 2025-01-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0005_expensescategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expensescategory',
            table='expense_categories',
        ),
    ]
