# Generated by Django 5.1.5 on 2025-02-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0006_alter_expensescategory_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.AlterField(
            model_name='expensessubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_subcategories', to='budget_api.expensescategory'),
        ),
        migrations.AlterField(
            model_name='incomesubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_subcategories', to='budget_api.incomecategory'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
