# Generated by Django 5.1.5 on 2025-02-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0007_remove_income_category_remove_income_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensessubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incomesubcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExpensesCategory',
        ),
        migrations.DeleteModel(
            name='ExpensesSubCategory',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
        migrations.DeleteModel(
            name='IncomeSubCategory',
        ),
    ]
