# Generated by Django 5.1.5 on 2025-02-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='icon_url',
        ),
    ]
